# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [195]:
# required imports
import numpy as np
import fnmatch
import os

Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [196]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [197]:
#Your code starts here   
# Using already created files f1.txt,f2.txt,f3.txt for IRS
try: # using exception handling to check if we are in "files" directory or not
    os.chdir("files") # if not, we change our directory to "files"
except: # this code block is executed if we are  in "files" directory
        print("""You are already in "files" directory""") 

totalFiles = os.listdir() # this lists total number of files in files directory
for i in totalFiles: # iterating over the list of total number of files
    if i != "synonyms.txt":
        files_dict[i] = (file_count) # creating a dictionary with key as file names and values as 0-n indeces
        file_count += 1 #incrementing file_count by one at each iteration

#Your code ends here       

You are already in "files" directory


Displaying the count of files.

In [198]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [199]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [200]:
#Your code starts here    
word = list() #make a list which will include words from each file

for i in files_dict: # loop through total number of files in dictionary(using keys as file names)
    fhand = open(i,"r") # for each file it is opened in read mode in outer loop
    for j in fhand: # make inner loop which will add text from each file into the "words" list
        s = j.lower().split() # the words in file are converted to lower case and splitted in a list
        word = s + word # the words are appended in the list
        
unique_word_set = set(word) # word list is converted to set , having unique words
print("Unique words in every file\n",unique_word_set,"\ncount of files",file_count) # print the unique set of words

#Your code ends here

Unique words in every file
 {'this', 'my', 'book', 'is', 'interesting', 'pen'} 
count of files 3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [201]:
#Your code starts here
TDM = np.zeros((file_count,len(unique_word_set))) # Term doc matrix is created using numpy array of size(filecount x length of set)
print(TDM,"\n")

unique_word_dic = dict() # creating a dictionary to include unique words present in unique_word_set
j = 0
for i in unique_word_set: # looping in set to include these words in dictionary 
    unique_word_dic[i] = j # using j as value of dictionary
    j += 1 # incrementing value corresponding to each key

print("dictionary of unique words\n", unique_word_dic,"\n")
print("dictionary of files\n", files_dict)

    
#Your code ends here

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

dictionary of unique words
 {'this': 0, 'my': 1, 'book': 2, 'is': 3, 'interesting': 4, 'pen': 5} 

dictionary of files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [202]:
#Your code starts here    
contents = list() #make a list which will include words from each file
words = str()

for i in files_dict: # loop through total number of files in dictionary(using keys as file names)
    fhand = open(i,"r") # for each file it is opened in read mode in outer loop
    words = fhand.read().lower() # file is read into words string
    words = words.split() # the string is splitted, to check if each unique word exists 
    for j in words: # inner loop checks for each splitted word
            TDM[files_dict.get(i,0)][unique_word_dic.get(j,0)]=1 # TDM is filled where words read from file match with unique words dictionary as corresponding indeces

print("Dictionary of Unique Words\n",unique_word_dic)
print("\nTerm Document Matrix\n",TDM)
#Your code ends here

Dictionary of Unique Words
 {'this': 0, 'my': 1, 'book': 2, 'is': 3, 'interesting': 4, 'pen': 5}

Term Document Matrix
 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [203]:
#Your code starts here    

col_vector = np.zeros((len(unique_word_set),1)) # making a column vector of size 6x1
print("colVector initially\n",col_vector)
#Your code ends here

colVector initially
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [204]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)

Query is: this is my ballpoint


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [205]:
lis = os.listdir() # storing all the files in a list 
for i in lis: # extracting out synonyms file from the list(loop is used in case any new file is added so we can find the file)
    if i == "synonyms.txt": # where file name matches condition returns true
        synonyms_file = i # store this file name in synonyms_file variable

syn_dic = dict() # declaring a synonym dictionary
fhand = open(synonyms_file) # reading the synonyms.txt

for i in fhand: # iterating over each line of file
    syn_split1 = i.strip().split(":") # spliting the values on basis of ":", strip() function will remove the empty spaces
    syn_key = syn_split1[0] # storing the values of string before the index 0 i.e the key value
    syn_split2 = i.strip().split(":")# spliting the values on basis of ":", strip() function will remove the empty spaces
    syn_val = syn_split2[1:] # storing the values of string after the key value till the end of line
    syn_dic[syn_key] = syn_val # adding key-value pair in dictionary
print("Synonym Dictionary\n",syn_dic) 



Synonym Dictionary
 {'write': [' compose, draft, author, create'], 'file': [' document, record, dossier, report'], 'example': [' illustration, instance, sample, demonstration'], 'query': [' question, inquiry, search, request'], 'synonym': [' equivalent, substitute, alternate, replacement'], 'retrieve': [' fetch, recover, obtain, bring back'], 'system': [' framework, structure, organization, arrangement'], 'search': [' seek, look for, explore, examine'], 'lost': [' misplaced, missing, forgotten, mislaid'], 'pen': [' write, ink, ballpoint, fountain'], 'paper': [' document, sheet, form, letter'], 'book': [' novel, volume, publication, tome'], 'read': [' peruse, scan, study, look at'], 'interesting': [' fascinating, engaging, intriguing, absorbing'], 'computer': [' machine, device, processor, laptop'], 'software': [' program, application, app, platform']}


### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [206]:

expanded_query = [] # declaring a list 
# Write code to expand the query using synonyms
#your code starts here
expanded_query = query.strip().split(" ") # storing the query words as a list by splitting on basis of delimiter " "
for i in expanded_query: #outer loop iterates for every word in expanded query
    for key,values in syn_dic.items(): #inner loop iterates for every key-value pair of dictionary
        list_val = values[0] # list_Val stores the string of values
        list_val = list_val.replace(" ","") # it remvoes all the empty spaces in list like " pen" -> "pen"(it will help in our if statement)
        list_val = list_val.strip().split(",") # the string is splitted on basis of ", " (space after comma is significant)
        if i in list_val: # if the word in 
            expanded_query.append(key)

#your code ends here

print("Expanded Query")
print(expanded_query)

Expanded Query
['this', 'is', 'my', 'ballpoint', 'pen']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [207]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary



In [208]:
#Your code starts here    
# for finding unique words set
for i in expanded_query: # outer loop iterates through every word of input string
    for j in unique_word_set: # inner loop iterates in the set of unique words
        if i==j: # condition checks if the word in string is present in set 
            col_vector[unique_word_dic.get(i,0)] = 1 # if word is found,  at relative index of colVector it is updated

print("col_vector after query\n",col_vector)
#Your code ends here

col_vector after query
 [[1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [209]:
#Your code starts here  
result = TDM.dot(col_vector) # the dot product of term doc matrix and colVector is taken to find the resultant matrix
print("result\n",result)
index = result.argmax()# argmax() function is used to find the index of max value in resultant vector
print("max_index\n",index) 
print("max\n",max(result)) # max of resultant vector is found
#Your code ends here

result
 [[3.]
 [4.]
 [2.]]
max_index
 1
max
 [4.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [210]:
#Your code starts here    

tuple1 = files_dict.items() # creates a tuple of key-value pair of dictionary
for i,j in tuple1: # using two variables , one for key and one for value
    if j==index: # if value matches our index of  max element of resultant vector
        print("file name\n",i) # we print that key(which corresponds to the file)
        break # if file name is found, we break the loop

fhand1 = open(i) #opening the file 
cont = fhand1.read() # reading the contents of file using read() funtion
print("\nContents of file\n",cont)

#Your code ends here

file name
 f2.txt

Contents of file
 This is my pen


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.