# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os

Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [2]:
# Here we have intialized some variables, you can add more if required.
file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [3]:
#Your code starts here   

# Using already created files f1.txt,f2.txt,f3.txt for IRS
try: # using exception handling to check if we are in "files" directory or not
    os.chdir("files") # if not, we change our directory to "files"
except: # this code block is executed if we are  in "files" directory
        print("""You are already in "files" directory""") 

totalFiles = os.listdir() # this lists total number of files in files directory
for i in totalFiles: # iterating over the list of total number of files
    if i != "synonyms.txt":
        files_dict[i] = (file_count) # creating a dictionary with key as file names and values as 0-n indeces
        file_count += 1 #incrementing file_count by one at each iteration

#Your code ends here       

Displaying the count of files.

In [4]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [5]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [6]:
#Your code starts here
    
word = list() #make a list which will include words from each file

for i in files_dict: # loop through total number of files in dictionary(using keys as file names)
    fhand = open(i,"r") # for each file it is opened in read mode in outer loop
    for j in fhand: # make inner loop which will add text from each file into the "words" list
        s = j.lower().split() # the words in file are converted to lower case and splitted in a list
        word = s + word # the words are appended in the list
        
unique_word_set = set(word) # word list is converted to set , having unique words
print("Unique words in every file\n",unique_word_set,"\ncount of files",file_count) # print the unique set of words

#Your code ends here

Unique words in every file
 {'this', 'interesting', 'book', 'is', 'my', 'pen'} 
count of files 3


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [7]:
#Your code starts here    
TDM = np.zeros((file_count,len(unique_word_set))) # Term doc matrix is created using numpy array of size(filecount x length of set)
print(TDM,"\n")

unique_word_dic = dict() # creating a dictionary to include unique words present in unique_word_set
j = 0
for i in unique_word_set: # looping in set to include these words in dictionary 
    unique_word_dic[i] = j # using j as value of dictionary
    j += 1 # incrementing value corresponding to each key

print("dictionary of unique words\n", unique_word_dic,"\n")
print("dictionary of files\n", files_dict)

#Your code ends here

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

dictionary of unique words
 {'this': 0, 'interesting': 1, 'book': 2, 'is': 3, 'my': 4, 'pen': 5} 

dictionary of files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [8]:
#Your code starts here    
contents = list() #make a list which will include words from each file
words = str()

for i in files_dict: # loop through total number of files in dictionary(using keys as file names)
    fhand = open(i,"r") # for each file it is opened in read mode in outer loop
    words = fhand.read().lower() # file is read into words string
    words = words.split() # the string is splitted, to check if each unique word exists 
    for j in words: # inner loop checks for each splitted word
            TDM[files_dict.get(i,0)][unique_word_dic.get(j,0)]=1 # TDM is filled where words read from file match with unique words dictionary as corresponding indeces

print("Dictionary of Unique Words\n",unique_word_dic)
print("\nTerm Document Matrix\n",TDM)

#Your code ends here

Dictionary of Unique Words
 {'this': 0, 'interesting': 1, 'book': 2, 'is': 3, 'my': 4, 'pen': 5}

Term Document Matrix
 [[1. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [9]:
#Your code starts here    
col_vector = np.zeros((len(unique_word_set),1)) # making a column vector of size 6x1
print("colVector initially\n",col_vector)
#Your code ends here

colVector initially
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [10]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary
query = input("\nWrite something for searching  ") # an input string is taken as input
print(query)



In [11]:
#Your code starts here    
query = query.split(" ") # the input string is splitted on basis on " " delimiter
for i in query: # outer loop iterates through every word of input string
    for j in unique_word_set: # inner loop iterates in the set of unique words
        if i==j: # condition checks if the word in string is present in set 
            col_vector[unique_word_dic.get(i,0)] = 1 # if word is found,  at relative index of colVector it is updated 
print("colVector after query\n",col_vector)
#Your code ends here

colVector after query
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [12]:
#Your code starts here  
result = TDM.dot(col_vector) # the dot product of term doc matrix and colVector is taken to find the resultant matrix
print("result\n",result)
index = result.argmax()# argmax() function is used to find the index of max value in resultant vector
print("max_index\n",index) 
print("max\n",max(result)) # max of resultant vector is found
#Your code ends here

result
 [[0.]
 [0.]
 [0.]]
max_index
 0
max
 [0.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [13]:
#Your code starts here  
  
tuple1 = files_dict.items() # creates a tuple of key-value pair of dictionary
for i,j in tuple1: # using two variables , one for key and one for value
    if j==index: # if value matches our index of  max element of resultant vector
        print("file name\n",i) # we print that key(which corresponds to the file)
        break # if file name is found, we break the loop

fhand1 = open(i) #opening the file 
cont = fhand1.read() # reading the contents of file using read() funtion
print("\nContents of file\n",cont)


#Your code ends here

file name
 f1.txt

Contents of file
 This is my book


Congratulations Now you are able to build your own small IRS.